'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { AlertTriangle, Bell, Bookmark, Check, ChevronRight, Clock3, Eye, Film, Heart, History, KeyRound, LayoutDashboard, Loader2, Lock, LogOut, RefreshCcw, Save, Settings, Shield, Star, Trash2, UserRound, Users } from 'lucide-react'
import { useAccount } from '@/hooks/useAccount'
import { useAuth } from '@/components/auth/AuthProvider'
import { useWatchProgress } from '@/hooks/useWatchProgress'
import { AccountAvatar } from '@/components/account/AccountAvatar'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { AccountSettings, PublicProfile, WatchlistStatus } from '@/lib/account-types'
import { savePublicProfile, usernameAvailable } from '@/lib/account-service'
import { database } from '@/lib/firebase'
import { ref, update } from 'firebase/database'
import { cn } from '@/lib/utils'

type Tab = 'overview' | 'profile' | 'movies' | 'notifications' | 'privacy' | 'security'
const tabs: Array<{ id: Tab; label: string; icon: typeof UserRound }> = [
  { id: 'overview', label: 'Tổng quan', icon: LayoutDashboard },
  { id: 'profile', label: 'Hồ sơ', icon: UserRound },
  { id: 'movies', label: 'Phim của tôi', icon: Bookmark },
  { id: 'notifications', label: 'Thông báo', icon: Bell },
  { id: 'privacy', label: 'Quyền riêng tư', icon: Shield },
  { id: 'security', label: 'Bảo mật', icon: Lock },
]
const statusLabels: Record<WatchlistStatus, string> = { planned: 'Muốn xem', watching: 'Đang xem', completed: 'Đã xem', favorite: 'Yêu thích' }
const formatDate = (time: number) => new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(time)
const formatDuration = (seconds: number) => `${Math.floor(seconds / 3600)} giờ ${Math.floor(seconds % 3600 / 60)} phút`

function MovieTile({ item, children }: { item: { movieSlug: string; movieTitle?: string; title?: string; poster?: string; percentage?: number }; children?: React.ReactNode }) {
  return <div className="group relative overflow-hidden rounded-xl border border-white/10 bg-white/[0.035]"><Link href={`/movie/${item.movieSlug}`} className="flex gap-3 p-3"><img src={item.poster || '/placeholder-movie.jpg'} alt="" className="h-24 w-16 shrink-0 rounded-lg object-cover" /><div className="min-w-0 flex-1 py-1"><h3 className="line-clamp-2 text-sm font-semibold text-white">{item.movieTitle || item.title}</h3>{item.percentage !== undefined && <><p className="mt-2 text-xs text-slate-400">Đã xem {Math.round(item.percentage)}%</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-purple-500" style={{ width: `${Math.min(100, item.percentage)}%` }} /></div></>}</div></Link>{children}</div>
}

export function AccountPage() {
  const router = useRouter(); const { user, loading: authLoading, logout, sendVerification, updateIdentity, deleteCurrentAccount, resetPassword } = useAuth()
  const account = useAccount(); const { records, episodeRecords } = useWatchProgress()
  const [tab, setTab] = useState<Tab>('overview'); const [draft, setDraft] = useState<PublicProfile | null>(null); const [usernameState, setUsernameState] = useState<'idle' | 'checking' | 'available' | 'taken'>('idle')
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [deleteOpen, setDeleteOpen] = useState(false); const [deletePassword, setDeletePassword] = useState('')

  useEffect(() => { if (!authLoading && !user) router.replace('/login?returnUrl=/account') }, [authLoading, router, user])
  useEffect(() => { if (account.profile) setDraft(account.profile) }, [account.profile])
  useEffect(() => {
    if (!user || !database || account.degraded || !account.settings.privacy.showRecentMovies) return
    const recent = Object.fromEntries(Object.values(records).sort((a, b) => b.updatedAt - a.updatedAt).slice(0, 12).map((item) => [item.movieSlug, { movieSlug: item.movieSlug, movieTitle: item.movieTitle, poster: item.poster || null, episodeName: item.episodeName, percentage: item.percentage, updatedAt: item.updatedAt }]))
    void update(ref(database), { [`publicRecent/${user.uid}`]: recent })
  }, [account.degraded, account.settings.privacy.showRecentMovies, records, user])
  useEffect(() => {
    if (!draft || draft.username === account.profile?.username) { setUsernameState('idle'); return }
    setUsernameState('checking'); const timer = window.setTimeout(() => { void usernameAvailable(draft.username, user?.uid).then((available) => setUsernameState(available ? 'available' : 'taken')) }, 400)
    return () => window.clearTimeout(timer)
  }, [account.profile?.username, draft?.username, user?.uid])

  const recent = useMemo(() => Object.values(records).sort((a, b) => b.updatedAt - a.updatedAt), [records])
  const watchedSeconds = useMemo(() => episodeRecords.reduce((sum, item) => sum + (item.secondsWatched || 0), 0), [episodeRecords])
  const watchlistItems = useMemo(() => Object.values(account.watchlist).sort((a, b) => b.updatedAt - a.updatedAt), [account.watchlist])
  const profileDirty = useMemo(() => Boolean(draft && account.profile && JSON.stringify(draft) !== JSON.stringify(account.profile)), [account.profile, draft])
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (!profileDirty) return; event.preventDefault(); event.returnValue = '' }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [profileDirty])

  if (authLoading || account.loading || !user || !account.profile || !draft) return <main className="flex min-h-[70vh] items-center justify-center bg-[#070912]"><Loader2 className="h-9 w-9 animate-spin text-purple-400" /></main>

  const saveProfile = async () => {
    if (account.degraded) { setMessage('Hãy khôi phục kết nối dữ liệu trước khi lưu hồ sơ.'); return }
    if (usernameState === 'taken' || usernameState === 'checking') return
    setSaving(true); setMessage(null)
    try { const saved = await savePublicProfile(user, account.profile!, draft); await updateIdentity(saved.displayName, saved.avatar); setDraft(saved); setMessage('Đã lưu hồ sơ.') }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Không lưu được hồ sơ.') }
    finally { setSaving(false) }
  }
  const updatePrivacy = (key: keyof AccountSettings['privacy'], value: boolean) => {
    if (account.degraded) { setMessage('Hãy khôi phục kết nối dữ liệu trước khi thay đổi quyền riêng tư.'); return }
    void account.updateSettings({ ...account.settings, privacy: { ...account.settings.privacy, [key]: value }, updatedAt: Date.now() })
  }

  return <main className="min-h-screen bg-[#070912] text-white">
    <div className="mx-auto grid w-full max-w-[1500px] gap-6 px-3 py-6 md:px-5 lg:grid-cols-[240px_minmax(0,1fr)] lg:py-10">
      <aside className="lg:sticky lg:top-24 lg:h-fit"><div className="mb-4 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.035] p-3"><AccountAvatar name={account.profile.displayName} src={account.profile.avatar} className="h-11 w-11 text-xs" /><div className="min-w-0"><p className="truncate text-sm font-semibold">{account.profile.displayName}</p><Link href={`/u/${account.profile.username}`} className="truncate text-xs text-purple-300 hover:underline">@{account.profile.username}</Link></div></div><nav className="flex gap-2 overflow-x-auto pb-2 lg:block lg:space-y-1 lg:overflow-visible">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} type="button" onClick={() => setTab(item.id)} className={cn('flex h-11 shrink-0 items-center gap-3 rounded-xl px-3 text-sm transition lg:w-full', tab === item.id ? 'bg-purple-500/15 text-purple-100' : 'text-slate-400 hover:bg-white/[0.05] hover:text-white')}><Icon className="h-4 w-4" />{item.label}{item.id === 'notifications' && account.unreadCount > 0 && <span className="ml-auto rounded-full bg-purple-500 px-2 py-0.5 text-[10px] font-bold text-white">{account.unreadCount}</span>}</button> })}</nav></aside>

      <section className="min-w-0">
        {account.error && <div role="alert" className="mb-5 flex flex-col gap-3 rounded-2xl border border-amber-400/20 bg-amber-400/[0.07] p-4 text-sm text-amber-100 sm:flex-row sm:items-center"><span className="flex min-w-0 flex-1 items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-300" /><span><strong className="block font-semibold">Đang hiển thị hồ sơ từ tài khoản Google</strong><span className="mt-1 block text-xs leading-5 text-amber-100/70">{account.error} Dữ liệu phim và thông báo sẽ đồng bộ lại khi kết nối được khôi phục.</span></span></span><Button type="button" size="sm" variant="outline" onClick={account.retry} className="shrink-0 border-amber-300/30 bg-transparent hover:bg-amber-300/10"><RefreshCcw className="mr-2 h-4 w-4" />Thử lại</Button></div>}
        {tab === 'security' && <div className="mb-5 max-w-3xl rounded-2xl border border-white/10 bg-white/[0.035] p-5"><h2 className="font-semibold">Phương thức đăng nhập</h2><div className="mt-3 flex flex-wrap gap-2">{user.providerData.map((provider) => <span key={provider.providerId} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-xs text-slate-300">{provider.providerId === 'google.com' ? <span className="font-black text-blue-400">G</span> : <KeyRound className="h-3.5 w-3.5 text-purple-300" />}{provider.providerId === 'google.com' ? 'Google' : 'Email và mật khẩu'}</span>)}</div></div>}
        {tab === 'profile' && <div className="mb-5 max-w-3xl rounded-2xl border border-white/10 bg-white/[0.035] p-5 sm:p-6"><h2 className="font-semibold">Thể loại yêu thích</h2><p className="mt-1 text-xs text-slate-500">Chọn tối đa 8 thể loại để thể hiện gu phim trên hồ sơ.</p><div className="mt-4 flex flex-wrap gap-2">{['Hành động', 'Tình cảm', 'Hài', 'Kinh dị', 'Khoa học viễn tưởng', 'Hoạt hình', 'Tâm lý', 'Hình sự', 'Phiêu lưu', 'Cổ trang', 'Tài liệu', 'Gia đình'].map((genre) => { const selected = draft.favoriteGenres.includes(genre); return <button key={genre} type="button" onClick={() => setDraft({ ...draft, favoriteGenres: selected ? draft.favoriteGenres.filter((item) => item !== genre) : draft.favoriteGenres.length < 8 ? [...draft.favoriteGenres, genre] : draft.favoriteGenres })} className={cn('rounded-full border px-3 py-2 text-xs transition', selected ? 'border-purple-400 bg-purple-500/15 text-purple-100' : 'border-white/10 text-slate-400 hover:border-white/25 hover:text-white')}>{selected && <Check className="mr-1 inline h-3 w-3" />}{genre}</button> })}</div></div>}
        {tab === 'overview' && <div className="space-y-6"><header><p className="text-sm text-purple-300">Không gian của bạn</p><h1 className="mt-1 text-3xl font-bold">Chào {account.profile.displayName}</h1><p className="mt-2 text-sm text-slate-400">Tiếp tục phim đang xem và quản lý hoạt động của bạn.</p></header><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[{ label: 'Phim đã mở', value: recent.length, icon: Film }, { label: 'Tập đã xem', value: episodeRecords.length, icon: History }, { label: 'Thời gian xem', value: formatDuration(watchedSeconds), icon: Clock3 }, { label: 'Danh sách phim', value: watchlistItems.length, icon: Bookmark }].map((stat) => <div key={stat.label} className="rounded-2xl border border-white/10 bg-white/[0.035] p-4"><stat.icon className="mb-3 h-5 w-5 text-purple-300" /><p className="text-xl font-bold">{stat.value}</p><p className="mt-1 text-xs text-slate-500">{stat.label}</p></div>)}</div><div><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Xem gần đây</h2><button onClick={() => setTab('movies')} className="text-xs text-purple-300">Xem tất cả</button></div>{recent.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{recent.slice(0, 6).map((item) => <MovieTile key={item.movieSlug} item={item} />)}</div> : <Empty icon={History} title="Chưa có lịch sử xem" text="Phim bạn xem sẽ xuất hiện ở đây." />}</div></div>}

        {tab === 'profile' && <div className="max-w-3xl space-y-6"><Header title="Hồ sơ cá nhân" text="Thông tin này xuất hiện trên trang công khai và trong phòng xem chung." /><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 sm:p-6"><div className="mb-6 flex flex-wrap items-center gap-4"><AccountAvatar name={draft.displayName} src={draft.avatar} className="h-20 w-20 text-lg" /><div><p className="font-medium">Ảnh đại diện</p><p className="mt-1 text-xs text-slate-500">Dùng ảnh Google hoặc nhập đường dẫn ảnh HTTPS.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Tên hiển thị"><Input value={draft.displayName} maxLength={40} onChange={(event) => setDraft({ ...draft, displayName: event.target.value })} /></Field><Field label="Username"><div><Input value={draft.username} maxLength={24} onChange={(event) => setDraft({ ...draft, username: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, '') })} /><p className={cn('mt-1 text-xs', usernameState === 'taken' ? 'text-red-300' : usernameState === 'available' ? 'text-emerald-300' : 'text-slate-500')}>{usernameState === 'checking' ? 'Đang kiểm tra…' : usernameState === 'taken' ? 'Username đã được sử dụng.' : usernameState === 'available' ? 'Username có thể sử dụng.' : '3–24 ký tự, chữ thường, số hoặc _.'}</p></div></Field><Field label="Ảnh đại diện"><Input value={draft.avatar || ''} onChange={(event) => setDraft({ ...draft, avatar: event.target.value })} placeholder="https://…" /></Field><Field label="Ảnh bìa"><Input value={draft.cover || ''} onChange={(event) => setDraft({ ...draft, cover: event.target.value })} placeholder="https://…" /></Field><div className="sm:col-span-2"><Field label="Giới thiệu"><textarea value={draft.bio || ''} onChange={(event) => setDraft({ ...draft, bio: event.target.value.slice(0, 180) })} rows={4} className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-purple-500" /><p className="mt-1 text-right text-xs text-slate-500">{draft.bio?.length || 0}/180</p></Field></div></div><div className="mt-6 flex items-center justify-end gap-3">{message && <p className="mr-auto text-sm text-slate-300">{message}</p>}<Button disabled={saving || usernameState === 'taken' || usernameState === 'checking' || !draft.displayName.trim()} onClick={() => void saveProfile()}><Save className="mr-2 h-4 w-4" />{saving ? 'Đang lưu…' : 'Lưu hồ sơ'}</Button></div></div></div>}

        {tab === 'movies' && <div className="space-y-7"><Header title="Phim của tôi" text="Lịch sử, phim đang xem và danh sách đã lưu." /><div><h2 className="mb-3 text-lg font-semibold">Danh sách phim</h2>{watchlistItems.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{watchlistItems.map((item) => <MovieTile key={item.movieSlug} item={item}><div className="flex items-center gap-2 border-t border-white/10 p-2"><select value={item.status} onChange={(event) => void account.setMovieStatus(item, event.target.value as WatchlistStatus)} className="h-9 min-w-0 flex-1 rounded-lg border border-white/10 bg-[#0b0f1a] px-2 text-xs"><option value="planned">Muốn xem</option><option value="watching">Đang xem</option><option value="completed">Đã xem</option><option value="favorite">Yêu thích</option></select><Button size="icon" variant="ghost" aria-label="Xóa khỏi danh sách" onClick={() => void account.setMovieStatus(item, null)} className="h-9 w-9"><Trash2 className="h-4 w-4" /></Button></div></MovieTile>)}</div> : <Empty icon={Bookmark} title="Danh sách đang trống" text="Lưu phim từ trang chi tiết để xem sau." />}</div><div><h2 className="mb-3 text-lg font-semibold">Toàn bộ lịch sử</h2>{recent.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{recent.map((item) => <MovieTile key={item.movieSlug} item={item} />)}</div> : <Empty icon={History} title="Chưa có lịch sử" text="Hãy bắt đầu một bộ phim." />}</div></div>}

        {tab === 'notifications' && <div className="space-y-5"><div className="flex items-end justify-between gap-3"><Header title="Thông báo" text="Tương tác mới từ cộng đồng CineMind." />{account.unreadCount > 0 && <Button size="sm" variant="outline" onClick={() => void account.markNotificationsRead()}>Đánh dấu đã đọc</Button>}</div>{account.notifications.length ? <div className="overflow-hidden rounded-2xl border border-white/10">{account.notifications.map((item) => <button key={item.id} onClick={() => void account.markNotificationsRead(item.id)} className={cn('flex w-full items-center gap-3 border-b border-white/10 p-4 text-left last:border-b-0', !item.read && 'bg-purple-500/[0.07]')}><AccountAvatar name={item.actorName} src={item.actorAvatar} className="h-10 w-10 text-xs" /><div className="min-w-0 flex-1"><p className="text-sm"><strong>{item.actorName}</strong> {item.type === 'follow' ? 'đã theo dõi bạn' : item.type === 'review_like' ? 'đã thích đánh giá của bạn' : item.type === 'review_reply' ? 'đã phản hồi đánh giá của bạn' : 'đã mời bạn xem chung'}</p><p className="mt-1 text-xs text-slate-500">{formatDate(item.createdAt)}</p></div>{!item.read && <span className="h-2 w-2 rounded-full bg-purple-400" />}</button>)}</div> : <Empty icon={Bell} title="Chưa có thông báo" text="Tương tác mới sẽ xuất hiện tại đây." />}</div>}

        {tab === 'privacy' && <div className="max-w-3xl space-y-5"><Header title="Quyền riêng tư" text="Bạn kiểm soát những gì người khác nhìn thấy." /><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.035]">{([{ key: 'profilePublic', label: 'Hồ sơ công khai', text: 'Cho phép người khác mở trang cá nhân của bạn.', icon: Eye }, { key: 'showRecentMovies', label: 'Hiển thị phim gần đây', text: 'Chỉ hiển thị tên phim, không hiện tiến độ chính xác.', icon: History }, { key: 'showWatchlist', label: 'Hiển thị danh sách phim', text: 'Cho phép mọi người xem các phim bạn đã lưu.', icon: Bookmark }, { key: 'showActivity', label: 'Hiển thị hoạt động', text: 'Hiển thị review và cập nhật danh sách.', icon: Users }, { key: 'allowWatchPartyInvites', label: 'Cho phép lời mời xem chung', text: 'Người khác có thể gửi lời mời phòng công khai.', icon: Film }] as const).map((item) => <label key={item.key} className="flex cursor-pointer items-center gap-4 border-b border-white/10 p-4 last:border-b-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/5"><item.icon className="h-5 w-5 text-purple-300" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{item.label}</span><span className="mt-1 block text-xs text-slate-500">{item.text}</span></span><input type="checkbox" checked={account.settings.privacy[item.key]} onChange={(event) => updatePrivacy(item.key, event.target.checked)} className="h-5 w-5 accent-purple-500" /></label>)}</div></div>}

        {tab === 'security' && <div className="max-w-3xl space-y-5"><Header title="Bảo mật" text="Xác minh email và quản lý quyền truy cập tài khoản." /><div className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-3"><MailStatus verified={user.emailVerified} /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{user.email}</p><p className="text-xs text-slate-500">{user.emailVerified ? 'Email đã được xác minh.' : 'Email chưa được xác minh.'}</p></div>{!user.emailVerified && <Button size="sm" variant="outline" onClick={() => void sendVerification().then(() => setMessage('Đã gửi email xác minh.'))}>Gửi xác minh</Button>}</div><div className="flex items-center gap-3 border-t border-white/10 pt-4"><KeyRound className="h-5 w-5 text-purple-300" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">Đặt lại mật khẩu</p><p className="text-xs text-slate-500">Nhận liên kết an toàn qua email.</p></div><Button size="sm" variant="outline" disabled={!user.email} onClick={() => user.email && void resetPassword(user.email).then(() => setMessage('Đã gửi email đặt lại mật khẩu.'))}>Gửi email</Button></div></div>{message && <p className="text-sm text-emerald-300">{message}</p>}<div className="rounded-2xl border border-red-500/20 bg-red-500/[0.05] p-5"><h2 className="font-semibold text-red-200">Xóa tài khoản</h2><p className="mt-1 text-sm text-slate-400">Thao tác này không thể hoàn tác. Bạn sẽ cần xác thực lại.</p>{deleteOpen ? <div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input value={deletePassword} onChange={(event) => setDeletePassword(event.target.value)} type="password" placeholder="Mật khẩu hiện tại (nếu có)" /><Button variant="destructive" onClick={() => void deleteCurrentAccount(deletePassword).then(() => router.replace('/'))}>Xác nhận xóa</Button><Button variant="ghost" onClick={() => setDeleteOpen(false)}>Hủy</Button></div> : <Button variant="destructive" className="mt-4" onClick={() => setDeleteOpen(true)}><Trash2 className="mr-2 h-4 w-4" />Xóa tài khoản</Button>}</div><Button variant="outline" onClick={() => void logout().then(() => router.replace('/'))}><LogOut className="mr-2 h-4 w-4" />Đăng xuất</Button></div>}
      </section>
    </div>
  </main>
}

function Header({ title, text }: { title: string; text: string }) { return <header><h1 className="text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-400">{text}</p></header> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
function Empty({ icon: Icon, title, text }: { icon: typeof UserRound; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.02] px-6 py-12 text-center"><Icon className="mx-auto h-8 w-8 text-slate-600" /><p className="mt-3 text-sm font-medium text-slate-300">{title}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div> }
function MailStatus({ verified }: { verified: boolean }) { return <span className={cn('flex h-10 w-10 items-center justify-center rounded-xl', verified ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-300')}>{verified ? <Check className="h-5 w-5" /> : <Settings className="h-5 w-5" />}</span> }
